/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import View=Laya.View;
import Dialog=Laya.Dialog;
import Scene=Laya.Scene;
var REG: Function = Laya.ClassUtils.regClass;
export module ui {
    export class APP_LoadingUI extends Laya.Scene {
		public progress:any;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("APP_Loading");
        }
    }
    REG("ui.APP_LoadingUI",APP_LoadingUI);
    export class APP_UpdateUI extends Laya.Scene {
		public progress:any;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("APP_Update");
        }
    }
    REG("ui.APP_UpdateUI",APP_UpdateUI);
    export class HallUI extends Laya.Scene {
		public combat:any;
		public market:any;
		public card:any;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Hall");
        }
    }
    REG("ui.HallUI",HallUI);
    export class playSceneUI extends Laya.Scene {
		public dapai:Laya.Button;
		public mopai:Laya.Button;
		public fapai:Laya.Button;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("playScene");
        }
    }
    REG("ui.playSceneUI",playSceneUI);
    export class RoomHallUI extends Laya.View {
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("RoomHall");
        }
    }
    REG("ui.RoomHallUI",RoomHallUI);
}
export module ui.Common.Game.Bet {
    export class BetUI extends Laya.Scene {
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Common/Game/Bet/Bet");
        }
    }
    REG("ui.Common.Game.Bet.BetUI",BetUI);
}
export module ui.Common.Game.BetButton {
    export class BetButtonUI extends Laya.View {
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Common/Game/BetButton/BetButton");
        }
    }
    REG("ui.Common.Game.BetButton.BetButtonUI",BetButtonUI);
}
export module ui.Common.Game {
    export class ChipUI extends Laya.View {
		public gold:Laya.Sprite;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Common/Game/Chip");
        }
    }
    REG("ui.Common.Game.ChipUI",ChipUI);
    export class DealUI extends Laya.View {
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Common/Game/Deal");
        }
    }
    REG("ui.Common.Game.DealUI",DealUI);
    export class FlickerUI extends Laya.View {
		public image_0:Laya.Sprite;
		public image_1:Laya.Sprite;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Common/Game/Flicker");
        }
    }
    REG("ui.Common.Game.FlickerUI",FlickerUI);
    export class PropUI extends Laya.View {
		public card:Laya.Sprite;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Common/Game/Prop");
        }
    }
    REG("ui.Common.Game.PropUI",PropUI);
    export class PropListUI extends Laya.View {
		public card_0:any;
		public card_1:any;
		public card_2:any;
		public card_3:any;
		public card_4:any;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Common/Game/PropList");
        }
    }
    REG("ui.Common.Game.PropListUI",PropListUI);
    export class TansAniUI extends Laya.View {
		public image:Laya.Sprite;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Common/Game/TansAni");
        }
    }
    REG("ui.Common.Game.TansAniUI",TansAniUI);
    export class UserLeftUI extends Laya.View {
		public userInfo:any;
		public propList:any;
		public rush:Laya.Sprite;
		public banker:Laya.Sprite;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Common/Game/UserLeft");
        }
    }
    REG("ui.Common.Game.UserLeftUI",UserLeftUI);
    export class UserRightUI extends Laya.View {
		public userInfo:any;
		public propList:any;
		public rush:Laya.Sprite;
		public banker:Laya.Sprite;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Common/Game/UserRight");
        }
    }
    REG("ui.Common.Game.UserRightUI",UserRightUI);
}
export module ui.Common.Game.PlayProp {
    export class PlayPropUI extends Laya.View {
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Common/Game/PlayProp/PlayProp");
        }
    }
    REG("ui.Common.Game.PlayProp.PlayPropUI",PlayPropUI);
}
export module ui.Common.Game.Rob {
    export class RobUI extends Laya.Scene {
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Common/Game/Rob/Rob");
        }
    }
    REG("ui.Common.Game.Rob.RobUI",RobUI);
}
export module ui.Common {
    export class GameQuickChatUI extends Laya.View {
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Common/GameQuickChat");
        }
    }
    REG("ui.Common.GameQuickChatUI",GameQuickChatUI);
    export class HealthGameReminderUI extends Laya.View {
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Common/HealthGameReminder");
        }
    }
    REG("ui.Common.HealthGameReminderUI",HealthGameReminderUI);
    export class RecordShowUI extends Laya.View {
		public players:Laya.Sprite;
		public close_btn:any;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Common/RecordShow");
        }
    }
    REG("ui.Common.RecordShowUI",RecordShowUI);
    export class VictoryShowUI extends Laya.View {
		public players:Laya.Sprite;
		public close_btn:any;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Common/VictoryShow");
        }
    }
    REG("ui.Common.VictoryShowUI",VictoryShowUI);
}
export module ui.Common.User {
    export class UserUI extends Laya.View {
		public UserImage:Laya.Image;
		public UserName:laya.display.Text;
		public UserScore:laya.display.Text;
		public ShowReady:any;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Common/User/User");
        }
    }
    REG("ui.Common.User.UserUI",UserUI);
}
export module ui.GameBull {
    export class DiskTopUI extends Laya.Scene {
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("GameBull/DiskTop");
        }
    }
    REG("ui.GameBull.DiskTopUI",DiskTopUI);
}
export module ui.Games.BenzBmw {
    export class BankerUI extends Laya.View {
		public plus_btn:any;
		public reduce_btn:any;
		public money_slider:any;
		public apply_btn:any;
		public close_btn:any;
		public money_text:laya.display.Text;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Games/BenzBmw/Banker");
        }
    }
    REG("ui.Games.BenzBmw.BankerUI",BankerUI);
    export class BenzBmwloadingUI extends Laya.View {
		public progress:any;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Games/BenzBmw/BenzBmwloading");
        }
    }
    REG("ui.Games.BenzBmw.BenzBmwloadingUI",BenzBmwloadingUI);
    export class ListUI extends Laya.View {
		public recharge_btn:any;
		public rule_btn:any;
		public setting_btn:any;
		public back_btn:any;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Games/BenzBmw/List");
        }
    }
    REG("ui.Games.BenzBmw.ListUI",ListUI);
    export class loadingUI extends Laya.View {
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Games/BenzBmw/loading");
        }
    }
    REG("ui.Games.BenzBmw.loadingUI",loadingUI);
    export class PlayerUI extends Laya.View {
		public close_btn:any;
		public confirm_btn:any;
		public player_list:Laya.List;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Games/BenzBmw/Player");
        }
    }
    REG("ui.Games.BenzBmw.PlayerUI",PlayerUI);
    export class PlayerlistUI extends Laya.View {
		public player_list:Laya.Sprite;
		public close_btn:any;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Games/BenzBmw/Playerlist");
        }
    }
    REG("ui.Games.BenzBmw.PlayerlistUI",PlayerlistUI);
    export class RoomselectionUI extends Laya.View {
		public back_btn:any;
		public about_btn:any;
		public senior_btn:any;
		public intermediate_btn:any;
		public primary_btn:any;
		public header_image:Laya.Sprite;
		public name_text:laya.display.Text;
		public money_text:laya.display.Text;
		public quick_btn:any;
		public rule_view:any;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Games/BenzBmw/Roomselection");
        }
    }
    REG("ui.Games.BenzBmw.RoomselectionUI",RoomselectionUI);
    export class RuleUI extends Laya.Dialog {
		public confirm_btn:any;
		public close_btn:any;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Games/BenzBmw/Rule");
        }
    }
    REG("ui.Games.BenzBmw.RuleUI",RuleUI);
    export class SettingUI extends Laya.View {
		public confirm_btn:any;
		public close_btn:any;
		public music_check:any;
		public bgm_check:any;
		public sound_check:any;
		public automatic_check:any;
		public night_check:any;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Games/BenzBmw/Setting");
        }
    }
    REG("ui.Games.BenzBmw.SettingUI",SettingUI);
    export class SpeakUI extends Laya.Scene {
		public message_list:Laya.List;
		public send_btn:any;
		public word_input:Laya.TextInput;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Games/BenzBmw/Speak");
        }
    }
    REG("ui.Games.BenzBmw.SpeakUI",SpeakUI);
    export class TableUI extends Laya.Scene {
		public go_btn:any;
		public car_image:Laya.Sprite;
		public dabaoshijie:Laya.Button;
		public dabenchi:Laya.Button;
		public dabaoma:Laya.Button;
		public dadazhong:Laya.Button;
		public baoshijie:Laya.Button;
		public benchi:Laya.Button;
		public baoma:Laya.Button;
		public dazhong:Laya.Button;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Games/BenzBmw/Table");
        }
    }
    REG("ui.Games.BenzBmw.TableUI",TableUI);
    export class TextfailureUI extends Laya.View {
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Games/BenzBmw/Textfailure");
        }
    }
    REG("ui.Games.BenzBmw.TextfailureUI",TextfailureUI);
    export class victoryUI extends Laya.View {
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Games/BenzBmw/victory");
        }
    }
    REG("ui.Games.BenzBmw.victoryUI",victoryUI);
    export class WithdrawmoneyUI extends Laya.View {
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Games/BenzBmw/Withdrawmoney");
        }
    }
    REG("ui.Games.BenzBmw.WithdrawmoneyUI",WithdrawmoneyUI);
}
export module ui.Games.Cow {
    export class CowCreateRoomUI extends Laya.View {
		public close_btn:any;
		public tabButtons:any;
		public btn_0:Laya.Sprite;
		public btn_1:Laya.Sprite;
		public btn_2:Laya.Sprite;
		public btn_3:Laya.Sprite;
		public btn_4:Laya.Sprite;
		public confirm_btn:any;
		public radios:Laya.Sprite;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Games/Cow/CowCreateRoom");
        }
    }
    REG("ui.Games.Cow.CowCreateRoomUI",CowCreateRoomUI);
    export class CowLoadingUI extends Laya.View {
		public progress:any;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Games/Cow/CowLoading");
        }
    }
    REG("ui.Games.Cow.CowLoadingUI",CowLoadingUI);
    export class CowRoomSelectionUI extends Laya.Scene {
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Games/Cow/CowRoomSelection");
        }
    }
    REG("ui.Games.Cow.CowRoomSelectionUI",CowRoomSelectionUI);
}
export module ui.Games.Dice {
    export class DiceUI extends Laya.Scene {
		public diceCup_group:Laya.Sprite;
		public dice_0:Laya.Sprite;
		public dice_1:Laya.Sprite;
		public dice_2:Laya.Sprite;
		public dice_ani:Laya.Animation;
		public play_btn:any;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Games/Dice/Dice");
        }
    }
    REG("ui.Games.Dice.DiceUI",DiceUI);
}
export module ui.Games.FiftyK {
    export class FiftyCreateRoomUI extends Laya.View {
		public confirm_btn:any;
		public close_btn:any;
		public radios:Laya.Sprite;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Games/FiftyK/FiftyCreateRoom");
        }
    }
    REG("ui.Games.FiftyK.FiftyCreateRoomUI",FiftyCreateRoomUI);
    export class FiveTenKloadingUI extends Laya.View {
		public progress:any;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Games/FiftyK/FiveTenKloading");
        }
    }
    REG("ui.Games.FiftyK.FiveTenKloadingUI",FiveTenKloadingUI);
    export class FiveTenKSelectionUI extends Laya.View {
		public btns_group:Laya.Sprite;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Games/FiftyK/FiveTenKSelection");
        }
    }
    REG("ui.Games.FiftyK.FiveTenKSelectionUI",FiveTenKSelectionUI);
}
export module ui.Games.FiveArching {
    export class FiveArchingCreateRoomUI extends Laya.View {
		public tabButtons:any;
		public btn_0:Laya.Sprite;
		public btn_1:Laya.Sprite;
		public check_1:any;
		public check_2:any;
		public close_btn:any;
		public confirm_btn:any;
		public radios:Laya.Sprite;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Games/FiveArching/FiveArchingCreateRoom");
        }
    }
    REG("ui.Games.FiveArching.FiveArchingCreateRoomUI",FiveArchingCreateRoomUI);
    export class FiveArchingloadingUI extends Laya.View {
		public progress:any;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Games/FiveArching/FiveArchingloading");
        }
    }
    REG("ui.Games.FiveArching.FiveArchingloadingUI",FiveArchingloadingUI);
    export class FiveArchingselectionUI extends Laya.View {
		public select_group:Laya.Sprite;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Games/FiveArching/FiveArchingselection");
        }
    }
    REG("ui.Games.FiveArching.FiveArchingselectionUI",FiveArchingselectionUI);
}
export module ui.Games.Fruit {
    export class FruitLoadingUI extends Laya.View {
		public progress:any;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Games/Fruit/FruitLoading");
        }
    }
    REG("ui.Games.Fruit.FruitLoadingUI",FruitLoadingUI);
    export class FruitSelectionUI extends Laya.View {
		public btns_group:Laya.Sprite;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Games/Fruit/FruitSelection");
        }
    }
    REG("ui.Games.Fruit.FruitSelectionUI",FruitSelectionUI);
    export class FruitTableUI extends Laya.Scene {
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Games/Fruit/FruitTable");
        }
    }
    REG("ui.Games.Fruit.FruitTableUI",FruitTableUI);
}
export module ui.Games.GoldenFlower {
    export class GoldenFlowerCreateRoomUI extends Laya.View {
		public confirm_btn:any;
		public close_btn:any;
		public radios:Laya.Sprite;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Games/GoldenFlower/GoldenFlowerCreateRoom");
        }
    }
    REG("ui.Games.GoldenFlower.GoldenFlowerCreateRoomUI",GoldenFlowerCreateRoomUI);
    export class GoldenFlowerLoadingUI extends Laya.View {
		public progress:any;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Games/GoldenFlower/GoldenFlowerLoading");
        }
    }
    REG("ui.Games.GoldenFlower.GoldenFlowerLoadingUI",GoldenFlowerLoadingUI);
    export class GoldenFlowerSelectionUI extends Laya.View {
		public btns_group:Laya.Sprite;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Games/GoldenFlower/GoldenFlowerSelection");
        }
    }
    REG("ui.Games.GoldenFlower.GoldenFlowerSelectionUI",GoldenFlowerSelectionUI);
}
export module ui.Games.Landlord {
    export class LandlordCreateRoomUI extends Laya.View {
		public confirm_btn:any;
		public close_btn:any;
		public radios:Laya.Sprite;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Games/Landlord/LandlordCreateRoom");
        }
    }
    REG("ui.Games.Landlord.LandlordCreateRoomUI",LandlordCreateRoomUI);
    export class LandlordLoadingUI extends Laya.View {
		public progress:any;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Games/Landlord/LandlordLoading");
        }
    }
    REG("ui.Games.Landlord.LandlordLoadingUI",LandlordLoadingUI);
    export class LandlordSelectionUI extends Laya.View {
		public btns_group:Laya.Sprite;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Games/Landlord/LandlordSelection");
        }
    }
    REG("ui.Games.Landlord.LandlordSelectionUI",LandlordSelectionUI);
}
export module ui.Games.RunsFast {
    export class RunFastCreateRoomUI extends Laya.View {
		public close_btn:any;
		public confirm_btn:any;
		public radios:Laya.Sprite;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Games/RunsFast/RunFastCreateRoom");
        }
    }
    REG("ui.Games.RunsFast.RunFastCreateRoomUI",RunFastCreateRoomUI);
    export class RunsFastLoadingUI extends Laya.View {
		public progress:any;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Games/RunsFast/RunsFastLoading");
        }
    }
    REG("ui.Games.RunsFast.RunsFastLoadingUI",RunsFastLoadingUI);
    export class RunsFastSelectionUI extends Laya.View {
		public btns_group:Laya.Sprite;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Games/RunsFast/RunsFastSelection");
        }
    }
    REG("ui.Games.RunsFast.RunsFastSelectionUI",RunsFastSelectionUI);
}
export module ui.Games.Stud {
    export class StudLoadingUI extends Laya.View {
		public progress:any;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Games/Stud/StudLoading");
        }
    }
    REG("ui.Games.Stud.StudLoadingUI",StudLoadingUI);
}
export module ui.Games.TenHalf {
    export class TenHalfLoadingUI extends Laya.Scene {
		public progress:any;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Games/TenHalf/TenHalfLoading");
        }
    }
    REG("ui.Games.TenHalf.TenHalfLoadingUI",TenHalfLoadingUI);
}
export module ui.Games.Texas {
    export class TexasCreateRoomUI extends Laya.View {
		public close_btn:any;
		public confirm_btn:any;
		public radios:Laya.Sprite;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Games/Texas/TexasCreateRoom");
        }
    }
    REG("ui.Games.Texas.TexasCreateRoomUI",TexasCreateRoomUI);
    export class TexasLoadingUI extends Laya.View {
		public progress:any;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Games/Texas/TexasLoading");
        }
    }
    REG("ui.Games.Texas.TexasLoadingUI",TexasLoadingUI);
    export class TexasSelectionUI extends Laya.Scene {
		public btns_group:Laya.Sprite;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Games/Texas/TexasSelection");
        }
    }
    REG("ui.Games.Texas.TexasSelectionUI",TexasSelectionUI);
}
export module ui.Games.Thanchicken {
    export class ThanChickenUI extends Laya.View {
		public btns_group:Laya.Sprite;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Games/Thanchicken/ThanChicken");
        }
    }
    REG("ui.Games.Thanchicken.ThanChickenUI",ThanChickenUI);
    export class ThanchickenCreateroomUI extends Laya.View {
		public check_1:any;
		public check_2:any;
		public close_btn:any;
		public confirm_btn:any;
		public tabButtons:any;
		public btn_0:Laya.Sprite;
		public btn_1:Laya.Sprite;
		public btn_2:Laya.Sprite;
		public radios:Laya.Sprite;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Games/Thanchicken/ThanchickenCreateroom");
        }
    }
    REG("ui.Games.Thanchicken.ThanchickenCreateroomUI",ThanchickenCreateroomUI);
    export class ThanChickenLoadingUI extends Laya.View {
		public progress:any;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Games/Thanchicken/ThanChickenLoading");
        }
    }
    REG("ui.Games.Thanchicken.ThanChickenLoadingUI",ThanChickenLoadingUI);
    export class ThanChickenSelectionUI extends Laya.View {
		public select_group:Laya.Sprite;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Games/Thanchicken/ThanChickenSelection");
        }
    }
    REG("ui.Games.Thanchicken.ThanChickenSelectionUI",ThanChickenSelectionUI);
}
export module ui.Games.ThirteenBets {
    export class ThirteenBetsUI extends Laya.Scene {
		public btns_group:Laya.Sprite;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Games/ThirteenBets/ThirteenBets");
        }
    }
    REG("ui.Games.ThirteenBets.ThirteenBetsUI",ThirteenBetsUI);
    export class ThirteenBetsCreateRoomUI extends Laya.View {
		public close_btn:any;
		public tabButtons:any;
		public btn_0:Laya.Sprite;
		public btn_1:Laya.Sprite;
		public btn_2:Laya.Sprite;
		public confirm_btn:any;
		public radios:Laya.Sprite;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Games/ThirteenBets/ThirteenBetsCreateRoom");
        }
    }
    REG("ui.Games.ThirteenBets.ThirteenBetsCreateRoomUI",ThirteenBetsCreateRoomUI);
    export class ThirteenBetsloadingUI extends Laya.View {
		public progress:any;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Games/ThirteenBets/ThirteenBetsloading");
        }
    }
    REG("ui.Games.ThirteenBets.ThirteenBetsloadingUI",ThirteenBetsloadingUI);
    export class ThirteenBetsSelectionUI extends Laya.View {
		public select_group:Laya.Sprite;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Games/ThirteenBets/ThirteenBetsSelection");
        }
    }
    REG("ui.Games.ThirteenBets.ThirteenBetsSelectionUI",ThirteenBetsSelectionUI);
}
export module ui.Games.ThreeDuke {
    export class ThreeDukeUI extends Laya.Scene {
		public btns_group:Laya.Sprite;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Games/ThreeDuke/ThreeDuke");
        }
    }
    REG("ui.Games.ThreeDuke.ThreeDukeUI",ThreeDukeUI);
    export class ThreeDukeCreateRoomUI extends Laya.Scene {
		public confirm_btn:any;
		public tabButtons:any;
		public btn_0:Laya.Sprite;
		public btn_1:Laya.Sprite;
		public btn_2:Laya.Sprite;
		public btn_3:Laya.Sprite;
		public btn_4:Laya.Sprite;
		public close_btn:any;
		public radios:Laya.Sprite;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Games/ThreeDuke/ThreeDukeCreateRoom");
        }
    }
    REG("ui.Games.ThreeDuke.ThreeDukeCreateRoomUI",ThreeDukeCreateRoomUI);
    export class ThreeDukeloadingUI extends Laya.Scene {
		public progress:any;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Games/ThreeDuke/ThreeDukeloading");
        }
    }
    REG("ui.Games.ThreeDuke.ThreeDukeloadingUI",ThreeDukeloadingUI);
    export class ThreeDukeSelectionUI extends Laya.Scene {
		public select_group:Laya.Sprite;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Games/ThreeDuke/ThreeDukeSelection");
        }
    }
    REG("ui.Games.ThreeDuke.ThreeDukeSelectionUI",ThreeDukeSelectionUI);
}
export module ui.Games.Twentyone {
    export class TwentyOneUI extends Laya.View {
		public btns_group:Laya.Sprite;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Games/Twentyone/TwentyOne");
        }
    }
    REG("ui.Games.Twentyone.TwentyOneUI",TwentyOneUI);
    export class TwentyoneCreateroomUI extends Laya.View {
		public check_1:any;
		public check_2:any;
		public close_btn:any;
		public confirm_btn:any;
		public tabButtons:any;
		public btn_0:Laya.Sprite;
		public btn_1:Laya.Sprite;
		public btn_2:Laya.Sprite;
		public btn_3:Laya.Sprite;
		public radios:Laya.Sprite;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Games/Twentyone/TwentyoneCreateroom");
        }
    }
    REG("ui.Games.Twentyone.TwentyoneCreateroomUI",TwentyoneCreateroomUI);
    export class TwentyOneloadingUI extends Laya.View {
		public progress:any;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Games/Twentyone/TwentyOneloading");
        }
    }
    REG("ui.Games.Twentyone.TwentyOneloadingUI",TwentyOneloadingUI);
    export class TwentyOneSelectionUI extends Laya.View {
		public select_group:Laya.Sprite;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Games/Twentyone/TwentyOneSelection");
        }
    }
    REG("ui.Games.Twentyone.TwentyOneSelectionUI",TwentyOneSelectionUI);
}
export module ui.Games.TwoEight {
    export class TwoEightUI extends Laya.Scene {
		public btns_group:Laya.Sprite;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Games/TwoEight/TwoEight");
        }
    }
    REG("ui.Games.TwoEight.TwoEightUI",TwoEightUI);
    export class TwoEightCreateroomUI extends Laya.View {
		public confirm_btn:any;
		public close_btn:any;
		public tabButtons:any;
		public btn_0:Laya.Sprite;
		public btn_1:Laya.Sprite;
		public btn_2:Laya.Sprite;
		public btn_3:Laya.Sprite;
		public btn_4:Laya.Sprite;
		public radios:Laya.Sprite;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Games/TwoEight/TwoEightCreateroom");
        }
    }
    REG("ui.Games.TwoEight.TwoEightCreateroomUI",TwoEightCreateroomUI);
    export class TwoEightloadingUI extends Laya.View {
		public progress:any;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Games/TwoEight/TwoEightloading");
        }
    }
    REG("ui.Games.TwoEight.TwoEightloadingUI",TwoEightloadingUI);
    export class TwoEightSelectionUI extends Laya.View {
		public select_group:Laya.Sprite;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Games/TwoEight/TwoEightSelection");
        }
    }
    REG("ui.Games.TwoEight.TwoEightSelectionUI",TwoEightSelectionUI);
}
export module ui.Hall.AgentPromotion {
    export class AgentPromotionUI extends Laya.View {
		public tabButtons:any;
		public btn_0:Laya.Sprite;
		public btn_1:Laya.Sprite;
		public btn_2:Laya.Sprite;
		public btn_3:Laya.Sprite;
		public btn_4:Laya.Sprite;
		public btn_5:Laya.Sprite;
		public btn_6:Laya.Sprite;
		public groups:Laya.Sprite;
		public close_btn:any;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Hall/AgentPromotion/AgentPromotion");
        }
    }
    REG("ui.Hall.AgentPromotion.AgentPromotionUI",AgentPromotionUI);
}
export module ui.Hall.Announcement {
    export class AnnouncementUI extends Laya.View {
		public close_btn:any;
		public tabButtons:any;
		public btn_0:Laya.Sprite;
		public btn_1:Laya.Sprite;
		public btn_2:Laya.Sprite;
		public groups:Laya.Sprite;
		public group_0:Laya.Sprite;
		public group_1:Laya.Sprite;
		public group_2:Laya.Sprite;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Hall/Announcement/Announcement");
        }
    }
    REG("ui.Hall.Announcement.AnnouncementUI",AnnouncementUI);
}
export module ui.Hall.CustomerService {
    export class CustomerServiceUI extends Laya.View {
		public close_btn:any;
		public ask_input:Laya.TextInput;
		public send_btn:any;
		public chat_list:Laya.List;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Hall/CustomerService/CustomerService");
        }
    }
    REG("ui.Hall.CustomerService.CustomerServiceUI",CustomerServiceUI);
}
export module ui.Hall.DissolutionRoom {
    export class DissolutionRoomUI extends Laya.View {
		public cancel_btn:any;
		public confirm_btn:any;
		public close_btn:any;
		public users_group:Laya.Sprite;
		public header_image:Laya.Sprite;
		public name_text:laya.display.Text;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Hall/DissolutionRoom/DissolutionRoom");
        }
    }
    REG("ui.Hall.DissolutionRoom.DissolutionRoomUI",DissolutionRoomUI);
    export class DissolutionRoomConfirmUI extends Laya.View {
		public close_btn:any;
		public confirm_btn:any;
		public cancel_btn:any;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Hall/DissolutionRoom/DissolutionRoomConfirm");
        }
    }
    REG("ui.Hall.DissolutionRoom.DissolutionRoomConfirmUI",DissolutionRoomConfirmUI);
}
export module ui.Hall.Hundredsofpeople {
    export class HundredspkUI extends Laya.View {
		public btn_0:any;
		public btn_1:any;
		public btn_2:any;
		public btn_3:any;
		public btn_4:any;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Hall/Hundredsofpeople/Hundredspk");
        }
    }
    REG("ui.Hall.Hundredsofpeople.HundredspkUI",HundredspkUI);
    export class HundredsSelectionUI extends Laya.View {
		public select_group:Laya.Sprite;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Hall/Hundredsofpeople/HundredsSelection");
        }
    }
    REG("ui.Hall.Hundredsofpeople.HundredsSelectionUI",HundredsSelectionUI);
}
export module ui.Hall {
    export class InvitationCodeUI extends Laya.Scene {
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Hall/InvitationCode");
        }
    }
    REG("ui.Hall.InvitationCodeUI",InvitationCodeUI);
}
export module ui.Hall.MailBox {
    export class MailUI extends Laya.View {
		public msgBox:Laya.Sprite;
		public alMsgName_text:laya.display.Text;
		public msgContent_text:laya.display.Text;
		public cancel_btn:any;
		public confirm_btn:any;
		public tabButtons:any;
		public btn_0:Laya.Sprite;
		public btn_1:Laya.Sprite;
		public msg_list:Laya.List;
		public close_btn:any;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Hall/MailBox/Mail");
        }
    }
    REG("ui.Hall.MailBox.MailUI",MailUI);
}
export module ui.Hall.Mall {
    export class MallUI extends Laya.View {
		public money_text:laya.display.Text;
		public diamond_text:laya.display.Text;
		public tabButtons:any;
		public btn_0:Laya.Sprite;
		public btn_1:Laya.Sprite;
		public btn_2:Laya.Sprite;
		public close_btn:any;
		public buyitem_lsit:Laya.List;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Hall/Mall/Mall");
        }
    }
    REG("ui.Hall.Mall.MallUI",MallUI);
}
export module ui.Hall.Promotions {
    export class PromotionsUI extends Laya.View {
		public close_btn:any;
		public tabButtons:any;
		public btn_0:Laya.Sprite;
		public btn_1:Laya.Sprite;
		public groups:Laya.Sprite;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Hall/Promotions/Promotions");
        }
    }
    REG("ui.Hall.Promotions.PromotionsUI",PromotionsUI);
}
export module ui.Hall.Recharge {
    export class RechargeUI extends Laya.View {
		public userMoney_text:laya.display.Text;
		public oneLevelMoney_text:laya.display.Text;
		public buyed_list:Laya.List;
		public userid_text:laya.display.Text;
		public vipRecharge_group:Laya.Sprite;
		public otherRecharge_group:Laya.Sprite;
		public money_input:Laya.TextInput;
		public clearInput_btn:any;
		public confirm_btn:any;
		public quickPush_btns:Laya.Sprite;
		public close_btn:any;
		public tabButtons:any;
		public btn_0:Laya.Sprite;
		public btn_1:Laya.Sprite;
		public btn_2:Laya.Sprite;
		public btn_3:Laya.Sprite;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Hall/Recharge/Recharge");
        }
    }
    REG("ui.Hall.Recharge.RechargeUI",RechargeUI);
}
export module ui.Hall.Safe {
    export class SafeUI extends Laya.View {
		public tabButtons:any;
		public btn_0:Laya.Sprite;
		public btn_1:Laya.Sprite;
		public btn_2:Laya.Sprite;
		public btn_3:Laya.Sprite;
		public btn_4:Laya.Sprite;
		public close_btn:any;
		public groups:Laya.Sprite;
		public access_group:Laya.Sprite;
		public money_input:Laya.TextInput;
		public reduce_btn:any;
		public plus_btn:any;
		public accessConfirm_btn:any;
		public clearInput_btn:any;
		public money_slider:any;
		public give_group:Laya.Sprite;
		public giveConfirm_btn:any;
		public giveCancel_btn:any;
		public giveRecords_btn:any;
		public recordUser_btn:any;
		public give_input:Laya.TextInput;
		public userid_input:Laya.TextInput;
		public moneys_group:Laya.Sprite;
		public money_text:laya.display.Text;
		public safe_text:laya.display.Text;
		public giveDetail_group:Laya.Sprite;
		public giveDetail_list:Laya.List;
		public access_list:Laya.List;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Hall/Safe/Safe");
        }
    }
    REG("ui.Hall.Safe.SafeUI",SafeUI);
}
export module ui.Hall.Set {
    export class SetUI extends Laya.View {
		public close_btn:any;
		public tabButtons:any;
		public btn_0:Laya.Sprite;
		public btn_1:Laya.Sprite;
		public btn_2:Laya.Sprite;
		public groups:Laya.Sprite;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Hall/Set/Set");
        }
    }
    REG("ui.Hall.Set.SetUI",SetUI);
}
export module ui.Hall.TeaHouse {
    export class CreateTeaHouseUI extends Laya.View {
		public military_btn:Laya.Sprite;
		public hall_btn:Laya.Sprite;
		public return_btn:any;
		public set_btn:Laya.Sprite;
		public houseList:Laya.List;
		public creat_btn:any;
		public join_btn:any;
		public houseHall:Laya.Sprite;
		public rankList:Laya.Sprite;
		public joinHouse:Laya.Sprite;
		public join_close_btn:any;
		public num_1:any;
		public num_2:any;
		public num_3:any;
		public num_4:any;
		public num_5:any;
		public num_6:any;
		public num_7:any;
		public num_8:any;
		public num_9:any;
		public search_btn:any;
		public num_0:any;
		public backspace:any;
		public search_text:Laya.TextInput;
		public join_houseName:laya.display.Text;
		public join_houseId:laya.display.Text;
		public creatHouse:Laya.Sprite;
		public creat_close_btn:any;
		public creat_sure_btn:any;
		public houseSet:Laya.Sprite;
		public house_set_close:any;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Hall/TeaHouse/CreateTeaHouse");
        }
    }
    REG("ui.Hall.TeaHouse.CreateTeaHouseUI",CreateTeaHouseUI);
    export class HouseItemUI extends Laya.View {
		public group:Laya.Box;
		public unselect:Laya.Sprite;
		public selected:Laya.Sprite;
		public houseHead:Laya.Sprite;
		public houseName:laya.display.Text;
		public houseId:laya.display.Text;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Hall/TeaHouse/HouseItem");
        }
    }
    REG("ui.Hall.TeaHouse.HouseItemUI",HouseItemUI);
}
export module ui.Hall.UserInfo {
    export class UserInfoUI extends Laya.Scene {
		public close_btn:any;
		public tabButtons:any;
		public btn_0:Laya.Sprite;
		public btn_1:Laya.Sprite;
		public btn_2:Laya.Sprite;
		public groups:Laya.Sprite;
		public userName_text:laya.display.Text;
		public userMoney_text:laya.display.Text;
		public confirmPass_btn:any;
		public oldPass_input:Laya.TextInput;
		public newPass_input:Laya.TextInput;
		public confirmPass_input:Laya.TextInput;
		public zfbName_input:Laya.TextInput;
		public zfbAccount_input:Laya.TextInput;
		public confirmzfb_btn:any;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Hall/UserInfo/UserInfo");
        }
    }
    REG("ui.Hall.UserInfo.UserInfoUI",UserInfoUI);
}
export module ui.Hall.Withdrawal {
    export class WithdrawalUI extends Laya.View {
		public widthDraw_group:Laya.Sprite;
		public money_input:Laya.TextInput;
		public userMoney_text:laya.display.Text;
		public record_btn:any;
		public bind_btn:any;
		public confirm_btn:any;
		public selectAll_btn:any;
		public clearInput_btn:any;
		public yhk_group:Laya.Sprite;
		public zfb_group:Laya.Sprite;
		public money_slider:any;
		public record_group:Laya.Sprite;
		public contact_btn:any;
		public recordg_btn:any;
		public tabButtons:any;
		public btn_0:Laya.Sprite;
		public btn_1:Laya.Sprite;
		public close_btn:any;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Hall/Withdrawal/Withdrawal");
        }
    }
    REG("ui.Hall.Withdrawal.WithdrawalUI",WithdrawalUI);
}
export module ui.Hundreds {
    export class BankerUserUI extends Laya.View {
		public UserName:laya.display.Text;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Hundreds/BankerUser");
        }
    }
    REG("ui.Hundreds.BankerUserUI",BankerUserUI);
    export class BetUI extends Laya.View {
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Hundreds/Bet");
        }
    }
    REG("ui.Hundreds.BetUI",BetUI);
}
export module ui.HundredsBull {
    export class HundredsBullUI extends Laya.Scene {
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("HundredsBull/HundredsBull");
        }
    }
    REG("ui.HundredsBull.HundredsBullUI",HundredsBullUI);
}
export module ui.Login {
    export class accountLoginUI extends Laya.View {
		public close_btn:any;
		public account_input:Laya.TextInput;
		public password_input:Laya.TextInput;
		public confirm_btn:any;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Login/accountLogin");
        }
    }
    REG("ui.Login.accountLoginUI",accountLoginUI);
    export class forgetPassUI extends Laya.View {
		public close_btn:any;
		public getCaptcha_btn:any;
		public confirm_btn:any;
		public account_input:Laya.TextInput;
		public captcha_input:Laya.TextInput;
		public confirmpass_input:Laya.TextInput;
		public password_input:Laya.TextInput;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Login/forgetPass");
        }
    }
    REG("ui.Login.forgetPassUI",forgetPassUI);
    export class LoginUI extends Laya.Scene {
		public chatLogin_btn:any;
		public QQLogin_btn:any;
		public quickLogin_btn:any;
		public accountLogin_btn:any;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Login/Login");
        }
    }
    REG("ui.Login.LoginUI",LoginUI);
    export class rigisteraccountUI extends Laya.View {
		public close_btn:any;
		public account_input:Laya.TextInput;
		public captcha_input:Laya.TextInput;
		public confirmpass_input:Laya.TextInput;
		public password_input:Laya.TextInput;
		public getCaptcha_btn:any;
		public confirm_btn:any;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Login/rigisteraccount");
        }
    }
    REG("ui.Login.rigisteraccountUI",rigisteraccountUI);
    export class wachatLoginUI extends Laya.View {
		public chat_image:Laya.Sprite;
		public close_btn:any;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Login/wachatLogin");
        }
    }
    REG("ui.Login.wachatLoginUI",wachatLoginUI);
}