export default  {
    BenzBmw: [
        "BenzBmw/Roomselection/Primaryfield.png",
        "BenzBmw/Roomselection/Intermediatefield.png",
        "BenzBmw/Roomselection/Advancedfield.png",
    ],
    Bull: [
        [
            "Cow/Selection/LowlevelField.png",
            "Cow/Selection/IntermediateField.png",
            "Cow/Selection/SeniorField.png",
        ],
        [
            "Cow/Selection/LowlevelField2.png",
            "Cow/Selection/IntermediateField2.png",
            "Cow/Selection/SeniorField2.png",
        ],
        [
            "Cow/Selection/LowlevelField3.png",
            "Cow/Selection/IntermediateField3.png",
            "Cow/Selection/SeniorField3.png",
        ],
        [
            "Cow/Selection/LowlevelField4.png",
            "Cow/Selection/IntermediateField4.png",
            "Cow/Selection/SeniorField4.png",
        ],
        [
            "Cow/Selection/LowlevelField5.png",
            "Cow/Selection/IntermediateField5.png",
            "Cow/Selection/SeniorField5.png",
        ],
    ],
    FiftyK: [
        "FiftyK/Selection/Primaryfield.png",
        "FiftyK/Selection/Intermediatefield.png",
        "FiftyK/Selection/Advancedfield.png",
    ],
    FiveArching: [
        [
            "FiveArching/Selection/Primaryfield.png",
            "FiveArching/Selection/Intermediatefield.png",
            "FiveArching/Selection/Advancedfield.png",
        ],
        [
            "FiveArching/Selection/Primaryfield(2).png",
            "FiveArching/Selection/Intermediatefield(2).png",
            "FiveArching/Selection/Advancedfield(2).png",
        ],
    ],
    Fruit: [
        "Fruit/Selection/Blueseven.png",
        "Fruit/Selection/Redseven.png",
        "Fruit/Selection/Seven.png",
    ],
    GoldenFlower: [
        "GoldenFlower/Selection/Primaryfield.png",
        "GoldenFlower/Selection/Intermediatefield.png",
        "GoldenFlower/Selection/Advancedfield.png",
    ],
    Landlord: [
        "Landlord/Selection/Primaryfield.png",
        "Landlord/Selection/Intermediatefield.png",
        "Landlord/Selection/Advancedfield.png",
    ],
    RunFast: [
        "RunFast/Selection/Primaryfield.png",
        "RunFast/Selection/Intermediatefield.png",
        "RunFast/Selection/Advancedfield.png",
    ],
    Texas: [
        "Texas/Selection/Primaryfield.png",
        "Texas/Selection/Intermediatefield.png",
        "Texas/Selection/Advancedfield.png",
    ],
    Thanchicken:[
        [
            "Thanchicken/Selection/Primaryfield.png",
            "Thanchicken/Selection/Intermediatefield.png",
            "Thanchicken/Selection/Advancedfield.png",
        ],
        [
            "Thanchicken/Selection/Primaryfield(2).png",
            "Thanchicken/Selection/Intermediatefield(2).png",
            "Thanchicken/Selection/Advancedfield(2).png",
        ],
        [
            "Thanchicken/Selection/Primaryfield(3).png",
            "Thanchicken/Selection/Intermediatefield(3).png",
            "Thanchicken/Selection/Advancedfield(3).png",
        ],
    ],
    ThirteenBets:[
        [
            "ThirteenBets/Selection/Primaryfield.png",
            "ThirteenBets/Selection/Intermediatefield.png",
            "ThirteenBets/Selection/Advancedfield.png",
        ],
        [
            "ThirteenBets/Selection/Primaryfield(2).png",
            "ThirteenBets/Selection/Intermediatefield(2).png",
            "ThirteenBets/Selection/Advancedfield(2).png",
        ],
        [
            "ThirteenBets/Selection/Primaryfield(3).png",
            "ThirteenBets/Selection/Intermediatefield(3).png",
            "ThirteenBets/Selection/Advancedfield(3).png",
        ],
    ],
    ThreeDuke:[
        [
            "ThreeDuke/Selection/Primaryfield.png",
            "ThreeDuke/Selection/Intermediatefield.png",
            "ThreeDuke/Selection/Advancedfield.png",
        ],
        [
            "ThreeDuke/Selection/Primaryfield(2).png",
            "ThreeDuke/Selection/Intermediatefield(2).png",
            "ThreeDuke/Selection/Advancedfield(2).png",
        ],
        [
            "ThreeDuke/Selection/Primaryfield(3).png",
            "ThreeDuke/Selection/Intermediatefield(3).png",
            "ThreeDuke/Selection/Advancedfield(3).png",
        ],
        [
            "ThreeDuke/Selection/Primaryfield(4).png",
            "ThreeDuke/Selection/Intermediatefield(4).png",
            "ThreeDuke/Selection/Advancedfield(4).png",
        ],
        [
            "ThreeDuke/Selection/Primaryfield(5).png",
            "ThreeDuke/Selection/Intermediatefield(5).png",
            "ThreeDuke/Selection/Advancedfield(5).png",
        ],
    ],
    Twentyone:[
        [
            "Twentyone/Selection/Primaryfield.png",
            "Twentyone/Selection/Intermediatefield.png",
            "Twentyone/Selection/Advancedfield.png",
        ],
        [
            "Twentyone/Selection/Primaryfield(2).png",
            "Twentyone/Selection/Intermediatefield(2).png",
            "Twentyone/Selection/Advancedfield(2).png",
        ],
        [
            "Twentyone/Selection/Primaryfield(3).png",
            "Twentyone/Selection/Intermediatefield(3).png",
            "Twentyone/Selection/Advancedfield(3).png",
        ],
        [
            "Twentyone/Selection/Primaryfield(4).png",
            "Twentyone/Selection/Intermediatefield(4).png",
            "Twentyone/Selection/Advancedfield(4).png",
        ],
        [
            "Twentyone/Selection/Primaryfield(5).png",
            "Twentyone/Selection/Intermediatefield(5).png",
            "Twentyone/Selection/Advancedfield(5).png",
        ],
    ],
    TwoEight:[
        [
            "TwoEight/Selection/Primaryfield.png",
            "TwoEight/Selection/Intermediatefield.png",
            "TwoEight/Selection/Advancedfield.png",
        ],
        [
            "TwoEight/Selection/Primaryfield(2).png",
            "TwoEight/Selection/Intermediatefield(2).png",
            "TwoEight/Selection/Advancedfield(2).png",
        ],
        [
            "TwoEight/Selection/Primaryfield(3).png",
            "TwoEight/Selection/Intermediatefield(3).png",
            "TwoEight/Selection/Advancedfield(3).png",
        ],
        [
            "TwoEight/Selection/Primaryfield(4).png",
            "TwoEight/Selection/Intermediatefield(4).png",
            "TwoEight/Selection/Advancedfield(4).png",
        ],
        [
            "TwoEight/Selection/Primaryfield(5).png",
            "TwoEight/Selection/Intermediatefield(5).png",
            "TwoEight/Selection/Advancedfield(5).png",
        ],
    ]
}