/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import CommonProgress from "./Application/GameCommon/widget/CommonProgress"
import CommonPopup from "./Application/GameCommonUI/CommonPopup"
import Button from "./Application/GameCommon/widget/Button"
import CommonToast from "./Application/GameCommonUI/CommonToast"
import BullGame from "./Application/GameAthleticsBull/Event/BullGame"
import UserPropList from "./Application/GameCommon/widget/UserPropList"
import User from "./Application/GameCommon/widget/User"
import Flicker from "./Application/GameCommon/widget/Flicker"
import PropList from "./Application/GameCommon/widget/PropList"
import Deal from "./Application/GameCommon/widget/Deal"
import Bet from "./Application/GameCommon/widget/Bet"
import Rob from "./Application/GameCommon/widget/Rob"
import TransAni from "./Application/GameCommon/widget/TransAni"
import CommonRadioGroup from "./Application/GameCommon/widget/CommonRadioGroup"
import CommonRadio from "./Application/GameCommon/widget/CommonRadio"
import CommonCheck from "./Application/GameCommon/widget/CommonCheck"
import GoldenFlowerGame from "./Application/GameAthleticsGoldenFlower/GoldenFlowerGame"
import Chip from "./Application/GameCommon/widget/Chip"
import Prop from "./Application/GameCommon/widget/Prop"
import CommonCreatRoom from "./Application/GameCommonUI/CommonCreatRoom"
import CommonGameTypeSelection from "./Application/GameCommonUI/CommonGameTypeSelection"
import FlutterText from "./Application/GameCommon/widget/FlutterText"
import HundredBet from "./Application/GameCommon/widget/HundredBet"
import Banker from "./Application/GameHundredsBenzBmw/Banker"
import CommonSlider from "./Application/GameCommon/widget/CommonSlider"
import Player from "./Application/GameHundredsBenzBmw/Player"
import Playerlist from "./Application/GameHundredsBenzBmw/Playerlist"
import Roomselection from "./Application/GameHundredsBenzBmw/Roomselection"
import Rule from "./Application/GameHundredsBenzBmw/Rule"
import Setting from "./Application/GameHundredsBenzBmw/Setting"
import Speak from "./Application/GameHundredsBenzBmw/Speak"
import Table from "./Application/GameHundredsBenzBmw/Table"
import HundredsBull from "./Application/GameHundredsBull/HundredsBull"
import DiceTable from "./Application/GameHundredsDice/DiceTable"
import FruitTable from "./Application/GameHundredsFruit/FruitTable"
import AgentPromotion from "./Application/Hall/AgentPromotion/AgentPromotion"
import CommonTabButtons from "./Application/GameCommon/widget/CommonTabButtons"
import Announcement from "./Application/Hall/Announcement/Announcement"
import CustomerService from "./Application/Hall/CustomerService/CustomerService"
import DissolutionRoom from "./Application/Hall/DissolutionRoom/DissolutionRoom"
import DissolutionRoomConfirm from "./Application/Hall/DissolutionRoom/DissolutionRoomConfirm"
import Hall from "./Application/Hall/Hall"
import Hundredspk from "./Application/Hall/Hundredsofpeople/Hundredspk"
import HundredsSelection from "./Application/Hall/Hundredsofpeople/HundredsSelection"
import InvitationCode from "./Application/Hall/InvitationCode"
import Mall from "./Application/Hall/Mall/Mall"
import Promotions from "./Application/Hall/Promotions/Promotions"
import Recharge from "./Application/Hall/Recharge/Recharge"
import Safe from "./Application/Hall/Safe/Safe"
import Set from "./Application/Hall/Set/Set"
import CreateTeaHouse from "./Application/Hall/TeaHouse/CreateTeaHouse"
import UserInfo from "./Application/Hall/UserInfo/UserInfo"
import VictoryShow from "./Application/Hall/VictoryShow"
import Withdrawal from "./Application/Hall/Withdrawal/Withdrawal"
import forgetPass from "./Application/Login/forgetPass"
import Login from "./Application/Login/Login"
import rigisteraccount from "./Application/Login/rigisteraccount"
import wachatLogin from "./Application/Login/wachatLogin"
import playScene from "./Application/playScene"
/*
* 游戏初始化配置;
*/
export default class GameConfig{
    static width:number=1920;
    static height:number=1080;
    static scaleMode:string="fixedwidth";
    static screenMode:string="none";
    static alignV:string="top";
    static alignH:string="left";
    static startScene:any="Hall/Hall.scene";
    static sceneRoot:string="";
    static debug:boolean=false;
    static stat:boolean=false;
    static physicsDebug:boolean=false;
    static exportSceneToJson:boolean=true;
    constructor(){}
    static init(){
        var reg: Function = Laya.ClassUtils.regClass;
        reg("Application/GameCommon/widget/CommonProgress.ts",CommonProgress);
        reg("Application/GameCommonUI/CommonPopup.ts",CommonPopup);
        reg("Application/GameCommon/widget/Button.ts",Button);
        reg("Application/GameCommonUI/CommonToast.ts",CommonToast);
        reg("Application/GameAthleticsBull/Event/BullGame.ts",BullGame);
        reg("Application/GameCommon/widget/UserPropList.ts",UserPropList);
        reg("Application/GameCommon/widget/User.ts",User);
        reg("Application/GameCommon/widget/Flicker.ts",Flicker);
        reg("Application/GameCommon/widget/PropList.ts",PropList);
        reg("Application/GameCommon/widget/Deal.ts",Deal);
        reg("Application/GameCommon/widget/Bet.ts",Bet);
        reg("Application/GameCommon/widget/Rob.ts",Rob);
        reg("Application/GameCommon/widget/TransAni.ts",TransAni);
        reg("Application/GameCommon/widget/CommonRadioGroup.ts",CommonRadioGroup);
        reg("Application/GameCommon/widget/CommonRadio.ts",CommonRadio);
        reg("Application/GameCommon/widget/CommonCheck.ts",CommonCheck);
        reg("Application/GameAthleticsGoldenFlower/GoldenFlowerGame.ts",GoldenFlowerGame);
        reg("Application/GameCommon/widget/Chip.ts",Chip);
        reg("Application/GameCommon/widget/Prop.ts",Prop);
        reg("Application/GameCommonUI/CommonCreatRoom.ts",CommonCreatRoom);
        reg("Application/GameCommonUI/CommonGameTypeSelection.ts",CommonGameTypeSelection);
        reg("Application/GameCommon/widget/FlutterText.ts",FlutterText);
        reg("Application/GameCommon/widget/HundredBet.ts",HundredBet);
        reg("Application/GameHundredsBenzBmw/Banker.ts",Banker);
        reg("Application/GameCommon/widget/CommonSlider.ts",CommonSlider);
        reg("Application/GameHundredsBenzBmw/Player.ts",Player);
        reg("Application/GameHundredsBenzBmw/Playerlist.ts",Playerlist);
        reg("Application/GameHundredsBenzBmw/Roomselection.ts",Roomselection);
        reg("Application/GameHundredsBenzBmw/Rule.ts",Rule);
        reg("Application/GameHundredsBenzBmw/Setting.ts",Setting);
        reg("Application/GameHundredsBenzBmw/Speak.ts",Speak);
        reg("Application/GameHundredsBenzBmw/Table.ts",Table);
        reg("Application/GameHundredsBull/HundredsBull.ts",HundredsBull);
        reg("Application/GameHundredsDice/DiceTable.ts",DiceTable);
        reg("Application/GameHundredsFruit/FruitTable.ts",FruitTable);
        reg("Application/Hall/AgentPromotion/AgentPromotion.ts",AgentPromotion);
        reg("Application/GameCommon/widget/CommonTabButtons.ts",CommonTabButtons);
        reg("Application/Hall/Announcement/Announcement.ts",Announcement);
        reg("Application/Hall/CustomerService/CustomerService.ts",CustomerService);
        reg("Application/Hall/DissolutionRoom/DissolutionRoom.ts",DissolutionRoom);
        reg("Application/Hall/DissolutionRoom/DissolutionRoomConfirm.ts",DissolutionRoomConfirm);
        reg("Application/Hall/Hall.ts",Hall);
        reg("Application/Hall/Hundredsofpeople/Hundredspk.ts",Hundredspk);
        reg("Application/Hall/Hundredsofpeople/HundredsSelection.ts",HundredsSelection);
        reg("Application/Hall/InvitationCode.ts",InvitationCode);
        reg("Application/Hall/Mall/Mall.ts",Mall);
        reg("Application/Hall/Promotions/Promotions.ts",Promotions);
        reg("Application/Hall/Recharge/Recharge.ts",Recharge);
        reg("Application/Hall/Safe/Safe.ts",Safe);
        reg("Application/Hall/Set/Set.ts",Set);
        reg("Application/Hall/TeaHouse/CreateTeaHouse.ts",CreateTeaHouse);
        reg("Application/Hall/UserInfo/UserInfo.ts",UserInfo);
        reg("Application/Hall/VictoryShow.ts",VictoryShow);
        reg("Application/Hall/Withdrawal/Withdrawal.ts",Withdrawal);
        reg("Application/Login/forgetPass.ts",forgetPass);
        reg("Application/Login/Login.ts",Login);
        reg("Application/Login/rigisteraccount.ts",rigisteraccount);
        reg("Application/Login/wachatLogin.ts",wachatLogin);
        reg("Application/playScene.ts",playScene);
    }
}
GameConfig.init();